steps:
  # STEP 1: TEST
  - name: 'python:3.13-slim'
    id: 'run-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --no-cache-dir -r requirements.txt
        pip install pytest httpx
        export TRADE_BOT_DB_URL="sqlite+aiosqlite:///:memory:"
        export CRYPTO_BACKEND_DB_URL="sqlite+aiosqlite:///:memory:"
        pytest

  # STEP 2: BUILD
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: [
      'build', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest',
      '.'
    ]

  # STEP 3: PUSH
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: [
      'push', 
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
    ]

  # STEP 4: DATABASE RESET (Running inside the newly built image)
  - name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
    id: 'reset-db'
    entrypoint: 'bash'
    secretEnv: ['DB_PASSWORD']
    args:
      - '-c'
      - |
        # Install wget to get the proxy
        apt-get update && apt-get install -y wget
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        
        # Start Proxy in background
        ./cloud_sql_proxy -instances=$_DB_INSTANCE_CONNECTION_NAME=tcp:5432 &
        sleep 8
        
        # Set Env for reset_db.py
        export DB_USER=$_DB_USER
        export DB_PASSWORD=$$DB_PASSWORD
        export INSTANCE_CONNECTION_NAME="localhost"
        
        python3 reset_db.py

  # STEP 5: DEPLOY
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$_DB_INSTANCE_CONNECTION_NAME'
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'
      - '--set-secrets'
      - 'NOWPAYMENTS_API_KEY=NOWPAYMENTS_API_KEY:latest'
      - '--set-secrets'
      - 'NOWPAYMENTS_IPN_SECRET=NOWPAYMENTS_IPN_SECRET:latest'
      - '--set-env-vars'
      - 'DB_USER=$_DB_USER'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=$_DB_INSTANCE_CONNECTION_NAME'

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest'