steps:
  # =====================================================
  # STEP 1: TEST
  # =====================================================
  # - name: 'python:3.13-slim'
  #   id: 'run-tests'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       pip install --no-cache-dir -r requirements.txt
  #       pip install pytest httpx
  #       export TRADE_BOT_DB_URL="sqlite+aiosqlite:///:memory:"
  #       export CRYPTO_BACKEND_DB_URL="sqlite+aiosqlite:///:memory:"
  #       pytest

  # =====================================================
  # STEP 2: BUILD
  # =====================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: [
      'build', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest',
      '.'
    ]

  # =====================================================
  # STEP 3: PUSH
  # =====================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: [
      'push', 
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
    ]

  # =====================================================
  # STEP 4: DATABASE RESET (Running inside the newly built image).
  # =====================================================
  - name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
    id: 'reset-db'
    entrypoint: 'bash'
    secretEnv: ['DB_PASSWORD']
    args:
      - '-c'
      - |
        # 1. Install wget to get the proxy
        apt-get update && apt-get install -y wget
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        
        # 2. Start Proxy in background
        ./cloud_sql_proxy -instances=$_DB_INSTANCE_CONNECTION_NAME=tcp:5432 &
        sleep 10
        
        # 3. Set Env for reset_db.py
        # Note: $$DB_PASSWORD (double $) is required to use secretEnv in bash
        export DB_USER=$_DB_USER
        export DB_PASSWORD=$$DB_PASSWORD
        export INSTANCE_CONNECTION_NAME="localhost"
        export DB_NAME_TRADE=trade_bot_db
        export DB_NAME_CRYPTO=crypto_backend_db
        
        echo "Starting Database Reset..."
        python3 reset_db.py

  # =====================================================
  # STEP 5: DEPLOY
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$_DB_INSTANCE_CONNECTION_NAME'
      
      # REMOVE the trailing commas at the end of these strings!
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'
      - '--set-secrets'
      - 'NOWPAYMENTS_API_KEY=NOWPAYMENTS_API_KEY:latest'
      - '--set-secrets'
      - 'NOWPAYMENTS_IPN_SECRET=NOWPAYMENTS_IPN_SECRET:latest'
      
      - '--set-env-vars'
      - 'DB_USER=$_DB_USER'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=$_DB_INSTANCE_CONNECTION_NAME'
      - '--set-env-vars'
      - 'DB_NAME_TRADE=trade_bot_db'
      - '--set-env-vars'
      - 'DB_NAME_CRYPTO=crypto_backend_db'
      - '--set-env-vars'
      - 'DISCORD_CLIENT_ID=1447721013260456058'
      - '--set-env-vars'
      - 'DISCORD_CLIENT_SECRET=YTvtWwgqc-p7PfIgaAorUNZFjvQI-pdw'
      - '--set-env-vars'
      - 'DISCORD_REDIRECT_URI=https://trade-backend-service-1054089939982.europe-west4.run.app/login/discord'
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_ID=1054089939982-e2umo92u5p7mh4gjm3hvknddprenho3k.apps.googleusercontent.com'
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_SECRET=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'
      - '--set-env-vars'
      - 'GOOGLE_REDIRECT_URI=https://trade-backend-service-1054089939982.europe-west4.run.app/login/google'
      - '--set-env-vars'
      - 'SECRET_KEY=73c680ee1ed6757da4430489104cc51e3f117199faae505ad41aff291f1b7b7f'

# ====================================================
# DEFINITIONS (MUST BE AT THE END).
# ====================================================

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
    env: 'DB_PASSWORD'

substitutions:
  _REGION: 'europe-west1'
  _REPO_NAME: 'app-repo'
  _IMAGE_NAME: 'trade-backend'
  _SERVICE_NAME: 'trade-backend-service'
  _DB_INSTANCE_CONNECTION_NAME: 'albion-bot-cheap-v1:europe-west1:albion-db-minimal'
  _DB_USER: 'postgres' 

options:
  pool:
    name: 'projects/albion-bot-cheap-v1/locations/europe-west1/workerPools/private-pool-1'
  # logging: CLOUD_LOGGING_ONLY
  # default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest'