steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: [
      'build', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest',
      '.'
    ]

  # =====================================================
  # STEP 3: PUSH
  # =====================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: [
      'push', 
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
    ]

  # =====================================================
  # STEP 4: DATABASE RESET
  # =====================================================
  - name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
    id: 'reset-db'
    entrypoint: 'bash'
    secretEnv: ['DB_PASSWORD']
    args:
      - '-c'
      - |
        echo ">>> Downloading Cloud SQL Proxy to /tmp..."
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /tmp/cloud_sql_proxy
        chmod +x /tmp/cloud_sql_proxy
        
        echo ">>> Starting Proxy (Private IP)..."
        # FIX: Use -ip_address_types=PRIVATE instead of -private-ip
        /tmp/cloud_sql_proxy -instances=$_DB_INSTANCE_CONNECTION_NAME=tcp:5432 -ip_address_types=PRIVATE &
        
        echo ">>> Waiting for Proxy..."
        sleep 5
        
        echo ">>> Running Reset Script..."
        export DB_USER=$_DB_USER
        export DB_PASSWORD="$$DB_PASSWORD"
        export INSTANCE_CONNECTION_NAME="127.0.0.1"
        export DB_NAME_TRADE=trade_bot_db
        export DB_NAME_CRYPTO=crypto_backend_db
        
        python3 reset_db.py

  # =====================================================
  # STEP 5: DEPLOY
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$_DB_INSTANCE_CONNECTION_NAME'
      
      # Secrets from Secret Manager
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'
      - '--set-secrets'
      - 'NOWPAYMENTS_API_KEY=NOWPAYMENTS_API_KEY:latest'
      - '--set-secrets'
      - 'NOWPAYMENTS_IPN_SECRET=NOWPAYMENTS_IPN_SECRET:latest'
      
      # Application Environment Variables
      - '--set-env-vars'
      - 'DB_USER=$_DB_USER'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=$_DB_INSTANCE_CONNECTION_NAME'
      - '--set-env-vars'
      - 'DB_NAME_TRADE=trade_bot_db'
      - '--set-env-vars'
      - 'DB_NAME_CRYPTO=crypto_backend_db'
      - '--set-env-vars'
      - 'DISCORD_CLIENT_ID=1447721013260456058'
      - '--set-env-vars'
      - 'DISCORD_CLIENT_SECRET=r2yH5aArXvTW264GdDNtnmzg6h_Q8l7_'
      - '--set-env-vars'
      - 'DISCORD_REDIRECT_URI=https://trade-backend-service-1014783260724.europe-west1.run.app/login/discord'
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_ID=1014783260724-k8qsvkb8nv0sasri7jsi1l5uj17ej51d.apps.googleusercontent.com'
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_SECRET=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'
      - '--set-env-vars'
      - 'GOOGLE_REDIRECT_URI=https://trade-backend-service-1014783260724.europe-west1.run.app/login/google'
      - '--set-env-vars'
      - 'SECRET_KEY=73c680ee1ed6757da4430489104cc51e3f117199faae505ad41aff291f1b7b7f'

# =====================================================
# DEFINITIONS
# =====================================================

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
    env: 'DB_PASSWORD'

substitutions:
  _REGION: 'europe-west1'
  _REPO_NAME: 'app-repo'
  _IMAGE_NAME: 'trade-backend'
  _SERVICE_NAME: 'trade-backend-service'
  _DB_INSTANCE_CONNECTION_NAME: 'albion-bot-cheap-v1:europe-west1:albion-db-minimal'
  _DB_USER: 'postgres'

options:
  pool:
    name: 'projects/albion-bot-cheap-v1/locations/europe-west1/workerPools/private-pool-1'
  logging: CLOUD_LOGGING_ONLY

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest'