steps:
  # =====================================================
  # STEP 1: TEST
  # =====================================================
  - name: 'python:3.11-slim'
    id: 'run-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        pip install --no-cache-dir -r requirements.txt
        pip install pytest httpx
        
        echo "Running tests..."
        # Dummy DBs for testing
        export TRADE_BOT_DB_URL="sqlite+aiosqlite:///:memory:"
        export CRYPTO_BACKEND_DB_URL="sqlite+aiosqlite:///:memory:"
        pytest

  # =====================================================
  # STEP 2: BUILD
  # =====================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: [
      'build', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA', 
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest',
      '.'
    ]

  # =====================================================
  # STEP 3: PUSH
  # =====================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: [
      'push', 
      # FIX: Explicitly push the specific SHA version required by the Deploy step
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
    ]

  # =====================================================
  # STEP 4: DEPLOY
  # =====================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      
      # 1. Connect to your Cloud SQL Instance
      - '--add-cloudsql-instances'
      - '$_DB_INSTANCE_CONNECTION_NAME'
      
      # 2. Inject the Secret from Secret Manager
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'

      # 3. Set other non-secret Env Vars
      - '--set-env-vars'
      - 'DB_USER=$_DB_USER'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=$_DB_INSTANCE_CONNECTION_NAME'
      - '--set-env-vars'
      - 'DB_NAME_TRADE=trade_bot_db'
      - '--set-env-vars'
      - 'DB_NAME_CRYPTO=crypto_backend_db'

# =====================================================
# VARIABLES
# =====================================================
substitutions:
  _REGION: 'europe-west4'
  _REPO_NAME: 'app-repo'  # Ensure you created this in Artifact Registry
  _IMAGE_NAME: 'trade-backend'
  _SERVICE_NAME: 'trade-backend-service'
  
  # Your Specific DB Details
  _DB_INSTANCE_CONNECTION_NAME: 'albiontradebot-backend:europe-west4:albion-trade-bot-db'
  _DB_USER: 'postgres' 

options:
  logging: CLOUD_LOGGING_ONLY
images:
  # This automatically pushes the 'latest' tag at the end of a successful build
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:latest'